---
#Created on 11 14, 2024
#@author: <Cui>
#@bref: 网络的各种配置


# 数据参数
data:
  download: false
  class_num: 10

# 网络参数
net:
  height: 28
  width: 28
  input_size: 784
#  hidden_layer_size: 128
#  output_size: 10
#  activation_function: ReLU

# 优化器参数
optimizer:
  type: Adam
  lr: 0.001
#  weight_decay: 0.0001

# 训练参数
train:
  mean: 0.1307
  std: 0.3081
  batch_size: 15
  epochs: 1

#模型参数
model:
  save_model: true

evl:
  use_save_model: true